---
name: Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  rubies:
    name: Ruby
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0"]
    runs-on: ubuntu-latest
    env:
      VERBOSE: "true"
      TIMEOUT: "30"
      LOW_TIMEOUT: "0.01"
      DRIVER: ruby
      REDIS_BRANCH: "7.0"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Print environment variables
        run: |
          echo "TIMEOUT=${TIMEOUT}"
          echo "LOW_TIMEOUT=${LOW_TIMEOUT}"
          echo "DRIVER=${DRIVER}"
          echo "REDIS_BRANCH=${REDIS_BRANCH}"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache local temporary directory
        uses: actions/cache@v3
        with:
          path: tmp
          key: "local-tmp-redis-7.0-on-ubuntu-latest"
      - name: Booting up Redis
        run: make start
      - name: Test
        run: bundle exec rake test:redis test:distributed
      - name: Shutting down Redis
        run: make stop

  drivers:
    name: Driver
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        driver: ["hiredis", "synchrony"]
    runs-on: ubuntu-latest
    env:
      VERBOSE: "true"
      TIMEOUT: "30"
      LOW_TIMEOUT: "0.01"
      DRIVER: ${{ matrix.driver }}
      REDIS_BRANCH: "7.0"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Print environment variables
        run: |
          echo "TIMEOUT=${TIMEOUT}"
          echo "LOW_TIMEOUT=${LOW_TIMEOUT}"
          echo "DRIVER=${DRIVER}"
          echo "REDIS_BRANCH=${REDIS_BRANCH}"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.4"
          bundler-cache: true
      - name: Cache local temporary directory
        uses: actions/cache@v3
        with:
          path: tmp
          key: "local-tmp-redis-7.0-on-ubuntu-latest"
      - name: Booting up Redis
        run: make start
      - name: Test
        run: bundle exec rake test:redis test:distributed
      - name: Shutting down Redis
        run: make stop

  redises:
    name: Redis
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        redis: ["7.1"]
    runs-on: ubuntu-latest
    env:
      VERBOSE: "true"
      TIMEOUT: "30"
      LOW_TIMEOUT: "0.14"
      DRIVER: ruby
      REDIS_BRANCH: ${{ matrix.redis }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Print environment variables
        run: |
          echo "TIMEOUT=${TIMEOUT}"
          echo "LOW_TIMEOUT=${LOW_TIMEOUT}"
          echo "DRIVER=${DRIVER}"
          echo "REDIS_BRANCH=${REDIS_BRANCH}"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.4"
          bundler-cache: true
      - name: Cache local temporary directory
        uses: actions/cache@v3
        with:
          path: tmp
          key: "local-tmp-redis-${{ matrix.redis }}-on-ubuntu-latest"
      - name: Booting up Redis
        run: make start
      - name: Test
        run: bundle exec rake test:redis test:distributed
      - name: Shutting down Redis
        run: make stop

  sentinel:
    name: Sentinel
    timeout-minutes: 30
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      VERBOSE: "true"
      TIMEOUT: "30"
      LOW_TIMEOUT: "0.14"
      DRIVER: ruby
      REDIS_BRANCH: "7.0"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Print environment variables
        run: |
          echo "TIMEOUT=${TIMEOUT}"
          echo "LOW_TIMEOUT=${LOW_TIMEOUT}"
          echo "DRIVER=${DRIVER}"
          echo "REDIS_BRANCH=${REDIS_BRANCH}"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.4"
          bundler-cache: true
      - name: Cache local temporary directory
        uses: actions/cache@v3
        with:
          path: tmp
          key: "local-tmp-redis-7.0-on-ubuntu-latest"
      - name: Booting up Redis
        run: make start_all
      - name: Test
        run: bundle exec rake test:sentinel
      - name: Shutting down Redis
        run: make stop_all

  cluster:
    name: Cluster
    timeout-minutes: 30
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      VERBOSE: "true"
      TIMEOUT: "30"
      LOW_TIMEOUT: "0.14"
      DRIVER: ruby
      REDIS_BRANCH: "7.0"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Print environment variables
        run: |
          echo "TIMEOUT=${TIMEOUT}"
          echo "LOW_TIMEOUT=${LOW_TIMEOUT}"
          echo "DRIVER=${DRIVER}"
          echo "REDIS_BRANCH=${REDIS_BRANCH}"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.4"
          bundler-cache: true
      - name: Cache local temporary directory
        uses: actions/cache@v3
        with:
          path: tmp
          key: "local-tmp-redis-7.0-on-ubuntu-latest"
      - name: Booting up Redis
        run: make start_all
      - name: Test
        run: bundle exec rake test:cluster
      - name: Shutting down Redis
        run: make stop_all
